# Shell variables
# Generated by 'wal'
wallpaper="/home/kyyneda/Pictures/sun.webp"

# Special
background='#0c060f'
foreground='#e4b9b2'
cursor='#e4b9b2'

# Colors
color0='#0c060f'
color1='#991634'
color2='#E30E2F'
color3='#8A0D43'
color4='#B0144E'
color5='#D62446'
color6='#D85847'
color7='#e4b9b2'
color8='#9f817c'
color9='#991634'
color10='#E30E2F'
color11='#8A0D43'
color12='#B0144E'
color13='#D62446'
color14='#D85847'
color15='#e4b9b2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
