--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/kyyneda/Pictures/sun.webp"

-- Special
background="#0c060f"
foreground="#e4b9b2"
cursor="#e4b9b2"

-- Colors
color0="#0c060f"
color1="#991634"
color2="#E30E2F"
color3="#8A0D43"
color4="#B0144E"
color5="#D62446"
color6="#D85847"
color7="#e4b9b2"
color8="#9f817c"
color9="#991634"
color10="#E30E2F"
color11="#8A0D43"
color12="#B0144E"
color13="#D62446"
color14="#D85847"
color15="#e4b9b2"
