foreground         #e4b9b2
background         #0c060f
background_opacity 1.0
cursor             #e4b9b2

active_tab_foreground     #0c060f
active_tab_background     #e4b9b2
inactive_tab_foreground   #e4b9b2
inactive_tab_background   #0c060f

active_border_color   #e4b9b2
inactive_border_color #0c060f
bell_border_color     #991634

color0       #0c060f
color8       #9f817c
color1       #991634
color9       #991634
color2       #E30E2F
color10      #E30E2F
color3       #8A0D43
color11      #8A0D43
color4       #B0144E
color12      #B0144E
color5       #D62446
color13      #D62446
color6       #D85847
color14      #D85847
color7       #e4b9b2
color15      #e4b9b2
